export enum PublicationStatus {
  PUBLISHED = 'PUBLISHED',
  PUBLICATION_PAUSED = 'PUBLICATION_PAUSED',
  TRANSACTION_IN_PROGRESS = 'TRANSACTION_IN_PROGRESS',
  TRANSACTION_COMPLETED = 'TRANSACTION_COMPLETED',
}
